techpack/data: Fix error cause a function declaration is deprecated
clang-15 warn:

../techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
rmnet_perf_free_hash_table()
                          ^
                           void
1 error generated.

Signed-off-by: hachiman270 <hachiman270@gmail.com>
Signed-off-by: Abhishek001konni <Abhishek001konni@gmail.com>